# Spring properties
spring:
  application:
     name: product-service
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.134:3306/iceproduct
  jpa:
    hibernate:
      ddl-auto: create-drop

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port
