# Spring properties
spring:
  application:
     name: quote-service

  data:
    mongodb:
      host: 192.168.31.134
      port: 27017

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port


# service name bindings
productService:
  url: product-service